type Team = {
  id: string;
  name: string;
  att: number;
  mid: number;
  def: number;
};

export const fixtures = (team: Team[]) => {
  return [
    {
      round: 1,
      games: [
        {
          round: 1,
          id: "r1g1",
          host: team[1],
          hostScore: 0,
          guest: team[0],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g2",
          host: team[2],
          hostScore: 0,
          guest: team[19],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g3",
          host: team[3],
          hostScore: 0,
          guest: team[18],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g4",
          host: team[4],
          hostScore: 0,
          guest: team[17],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g5",
          host: team[5],
          hostScore: 0,
          guest: team[16],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g6",
          host: team[6],
          hostScore: 0,
          guest: team[15],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g7",
          host: team[7],
          hostScore: 0,
          guest: team[14],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g8",
          host: team[8],
          hostScore: 0,
          guest: team[13],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g9",
          host: team[9],
          hostScore: 0,
          guest: team[12],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 1,
          id: "r1g10",
          host: team[10],
          hostScore: 0,
          guest: team[11],
          guestScore: 0,
          isPlayed: false,
        },
      ],
    },
    {
      round: 2,
      games: [
        {
          round: 2,
          id: "r2g1",
          host: team[19],
          hostScore: 0,
          guest: team[1],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g2",
          host: team[18],
          hostScore: 0,
          guest: team[2],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g3",
          host: team[17],
          hostScore: 0,
          guest: team[3],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g4",
          host: team[16],
          hostScore: 0,
          guest: team[4],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g5",
          host: team[15],
          hostScore: 0,
          guest: team[5],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g6",
          host: team[14],
          hostScore: 0,
          guest: team[6],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g7",
          host: team[13],
          hostScore: 0,
          guest: team[7],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g8",
          host: team[12],
          hostScore: 0,
          guest: team[8],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g9",
          host: team[11],
          hostScore: 0,
          guest: team[9],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 2,
          id: "r2g10",
          host: team[0],
          hostScore: 0,
          guest: team[10],
          guestScore: 0,
          isPlayed: false,
        },
      ],
    },
    {
      round: 3,
      games: [
        {
          round: 3,
          id: "r3g1",
          host: team[1],
          hostScore: 0,
          guest: team[18],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g2",
          host: team[2],
          hostScore: 0,
          guest: team[17],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g3",
          host: team[3],
          hostScore: 0,
          guest: team[16],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g4",
          host: team[4],
          hostScore: 0,
          guest: team[15],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g5",
          host: team[5],
          hostScore: 0,
          guest: team[14],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g6",
          host: team[6],
          hostScore: 0,
          guest: team[13],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g7",
          host: team[7],
          hostScore: 0,
          guest: team[12],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g8",
          host: team[8],
          hostScore: 0,
          guest: team[11],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g9",
          host: team[9],
          hostScore: 0,
          guest: team[10],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 3,
          id: "r3g10",
          host: team[19],
          hostScore: 0,
          guest: team[0],
          guestScore: 0,
          isPlayed: false,
        },
      ],
    },
    {
      round: 4,
      games: [
        {
          round: 4,
          id: "r4g1",
          host: team[17],
          hostScore: 0,
          guest: team[1],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g2",
          host: team[16],
          hostScore: 0,
          guest: team[2],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g3",
          host: team[15],
          hostScore: 0,
          guest: team[3],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g4",
          host: team[15],
          hostScore: 0,
          guest: team[4],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g5",
          host: team[13],
          hostScore: 0,
          guest: team[5],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g6",
          host: team[12],
          hostScore: 0,
          guest: team[6],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g7",
          host: team[11],
          hostScore: 0,
          guest: team[7],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g8",
          host: team[10],
          hostScore: 0,
          guest: team[8],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g9",
          host: team[0],
          hostScore: 0,
          guest: team[9],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 4,
          id: "r4g10",
          host: team[18],
          hostScore: 0,
          guest: team[19],
          guestScore: 0,
          isPlayed: false,
        },
      ],
    },
    {
      round: 5,
      games: [
        {
          round: 5,
          id: "r5g1",
          host: team[1],
          hostScore: 0,
          guest: team[16],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g2",
          host: team[2],
          hostScore: 0,
          guest: team[15],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g3",
          host: team[3],
          hostScore: 0,
          guest: team[14],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g4",
          host: team[4],
          hostScore: 0,
          guest: team[13],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g5",
          host: team[5],
          hostScore: 0,
          guest: team[12],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g6",
          host: team[6],
          hostScore: 0,
          guest: team[11],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g7",
          host: team[7],
          hostScore: 0,
          guest: team[10],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g8",
          host: team[8],
          hostScore: 0,
          guest: team[9],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g9",
          host: team[19],
          hostScore: 0,
          guest: team[17],
          guestScore: 0,
          isPlayed: false,
        },
        {
          round: 5,
          id: "r5g10",
          host: team[18],
          hostScore: 0,
          guest: team[0],
          guestScore: 0,
          isPlayed: false,
        },
      ],
    },
  ];
};
